#!/bin/sh -e

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 force-reload || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}

if [ -n "$2" ]; then
    if [ -e /etc/apache2/mods-enabled/proxy_wstunnel.load ]; then
        reload_apache
    fi
    exit 0
fi

if [ -e /etc/apache2/apache2.conf ]; then
    a2enmod proxy_wstunnel >/dev/null || true
    reload_apache
fi
